services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: myjenkins
    user: root
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8443:8080"  # Gunakan port 8443 untuk akses HTTP
      - "50000:50000"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped