services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: myjenkins
    user: root
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins.jks:/var/lib/jenkins/jenkins.jks
    ports:
      - "8443:8443"
      - "50000:50000"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped
    command: >
      --httpPort=-1
      --httpsPort=8443
      --httpsKeyStore=/var/lib/jenkins/jenkins.jks
      --httpsKeyStorePassword=mypassword
